### ISSUE TITLE
Crash with `InternalException` after report an error

### ISSUE THREAD

**Issue by dannypsnl** [aya-prover/aya-dev#1016]
I expect the missing pattern for `A : Type`

```aya
open import Primitives

def isContr (A : Type) => Sig (a : A) ** (∀ b -> a = b)

def fail (A : Type) : isContr A -> Fn (x y : A) -> x = y
  | (a, C) => \x y => {??}
```

will report an error

```
Error: The tuple pattern
         (a, C)
       splits only on sigma types, while the actual type
         Type 0
       does not look like one
```

Aya also do so, but it also fall into `InternalException` later.

```
Error: The tuple pattern
         (a, C)
       splits only on sigma types, while the actual type
         Type 0
       does not look like one

org.aya.util.error.InternalException: ?
	at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:124)
	at org.aya.tyck.unify.Synthesizer.synthesize(Synthesizer.java:61)
	at org.aya.tyck.unify.Synthesizer.tryPress(Synthesizer.java:32)
	at org.aya.tyck.unify.Synthesizer.synthesize(Synthesizer.java:97)
	at org.aya.tyck.unify.DoubleChecker.inherit(DoubleChecker.java:36)
	at org.aya.tyck.unify.Unifier.solveMetaWHNF(Unifier.java:136)
	at org.aya.tyck.unify.Unifier.solveMeta(Unifier.java:83)
	at org.aya.tyck.unify.TermComparator.compare(TermComparator.java:134)
	at org.aya.tyck.unify.TermComparator.compare(TermComparator.java:116)
	at org.aya.tyck.tycker.UnifiedTycker.unifyTy(UnifiedTycker.java:188)
	at org.aya.tyck.tycker.UnifiedTycker.unifyTyReported(UnifiedTycker.java:75)
	at org.aya.tyck.tycker.UnifiedTycker.unifyTyReported(UnifiedTycker.java:60)
	at org.aya.tyck.pat.PatternTycker.lambda$doTyck$0(PatternTycker.java:109)
	at org.aya.tyck.tycker.MockTycker.subscoped(MockTycker.java:89)
	at org.aya.tyck.tycker.LetListTycker.subscoped(LetListTycker.java:31)
	at org.aya.tyck.pat.PatternTycker.doTyck(PatternTycker.java:106)
	at org.aya.tyck.pat.PatternTycker.lambda$updateSig$2(PatternTycker.java:264)
	at org.aya.tyck.tycker.TracedTycker.traced(TracedTycker.java:46)
	at org.aya.tyck.pat.PatternTycker.lambda$updateSig$3(PatternTycker.java:263)
	at org.aya.tyck.pat.PatternTycker.onTyck(PatternTycker.java:250)
	at org.aya.tyck.pat.PatternTycker.updateSig(PatternTycker.java:260)
	at org.aya.tyck.pat.PatternTycker.tyck(PatternTycker.java:219)
	at org.aya.tyck.pat.ClauseTycker.lambda$checkLhs$12(ClauseTycker.java:136)
	at org.aya.tyck.tycker.MockTycker.subscoped(MockTycker.java:89)
	at org.aya.tyck.tycker.LetListTycker.subscoped(LetListTycker.java:31)
	at org.aya.tyck.pat.ClauseTycker.checkLhs(ClauseTycker.java:129)
	at org.aya.tyck.pat.ClauseTycker.lambda$checkAllLhs$1(ClauseTycker.java:77)
	at org.aya.tyck.tycker.TracedTycker.traced(TracedTycker.java:46)
	at org.aya.tyck.pat.ClauseTycker.lambda$checkAllLhs$2(ClauseTycker.java:75)
	at kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:409)
	at kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:163)
	at org.aya.tyck.pat.ClauseTycker.checkAllLhs(ClauseTycker.java:75)
	at org.aya.tyck.pat.ClauseTycker.elabClausesClassified(ClauseTycker.java:57)
	at org.aya.tyck.StmtTycker.doTyck(StmtTycker.java:100)
	at org.aya.tyck.StmtTycker.lambda$traced$1(StmtTycker.java:54)
	at org.aya.tyck.tycker.MockTycker.subscoped(MockTycker.java:89)
	at org.aya.tyck.tycker.LetListTycker.subscoped(LetListTycker.java:31)
	at org.aya.tyck.StmtTycker.lambda$traced$2(StmtTycker.java:54)
	at org.aya.tyck.tycker.TracedTycker.traced(TracedTycker.java:46)
	at org.aya.tyck.StmtTycker.traced(StmtTycker.java:53)
	at org.aya.tyck.StmtTycker.tyck(StmtTycker.java:58)
	at org.aya.tyck.order.AyaSccTycker.checkBody(AyaSccTycker.java:172)
	at org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:161)
	at org.aya.tyck.order.AyaSccTycker.checkUnit(AyaSccTycker.java:125)
	at org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:63)
	at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:441)
	at org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:42)
	at org.aya.cli.library.LibraryModuleLoader.load(LibraryModuleLoader.java:79)
	at org.aya.resolve.module.CachedModuleLoader.lambda$load$0(CachedModuleLoader.java:32)
	at kala.collection.mutable.MutableTreeMap.getOrPut(MutableTreeMap.java:483)
	at org.aya.resolve.module.CachedModuleLoader.load(CachedModuleLoader.java:32)
	at org.aya.resolve.module.ModuleLoader.load(ModuleLoader.java:77)
	at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckOne(LibraryCompiler.java:377)
	at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckSCC(LibraryCompiler.java:364)
	at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.function.CheckedConsumer.accept(CheckedConsumer.java:46)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:441)
	at kala.collection.base.Traversable.forEachChecked(Traversable.java:959)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:264)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:233)
	at org.aya.cli.utils.CompilerUtil.catching(CompilerUtil.java:30)
	at org.aya.cli.library.LibraryCompiler.start(LibraryCompiler.java:154)
	at org.aya.cli.library.LibraryCompiler.compile(LibraryCompiler.java:96)
	at org.aya.cli.console.Main.doCompile(Main.java:100)
	at org.aya.cli.console.Main.call(Main.java:54)
	at org.aya.cli.console.Main.call(Main.java:34)
	at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
	at picocli.CommandLine.access$1500(CommandLine.java:148)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at picocli.CommandLine.execute(CommandLine.java:2170)
	at org.aya.cli.console.Main.main(Main.java:36)
?
Please report the stacktrace to the developers so a better error handling could be made.
Don't forget to inform the version of Aya you're using and attach your code for reproduction.
Internal error
```

**Comment by ice1000** [comment]
The code is not right, you need to first pattern match on `A` (by just writing `A`, i.e. using a variable pattern), then the sigma.

**Comment by ice1000** [comment]
But we need to fix the error

**Comment by dannypsnl** [comment]
I know the code is wrong, therefore, there is an error. But I have no other example to trigger the InternalException, since I’m accidentally triggering it.
