### ISSUE TITLE
??? NPE

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#1058]
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Unknown Source)
	at aya.syntax/org.aya.syntax.ref.QName.<init>(Unknown Source)
	at aya.syntax/org.aya.prettier.BasePrettier.linkIdOf(Unknown Source)
	at aya.cli.impl/org.aya.cli.literate.SyntaxHighlight.linkDef(Unknown Source)
	at aya.cli.impl/org.aya.cli.literate.SyntaxHighlight.visitVarDecl(Unknown Source)
	at aya.syntax/org.aya.syntax.concrete.stmt.StmtVisitor.visitVars(Unknown Source)
	at aya.syntax/org.aya.syntax.concrete.stmt.StmtVisitor.accept(Unknown Source)
	at aya.syntax/org.aya.syntax.concrete.stmt.StmtVisitor.accept(Unknown Source)
	at kala.collection@0.73.0/kala.collection.immutable.ImmutableVectors$Vector1.forEach(Unknown Source)
	at aya.syntax/org.aya.syntax.concrete.stmt.StmtVisitor.accept(Unknown Source)
	at aya.syntax/org.aya.syntax.concrete.stmt.StmtVisitor.accept(Unknown Source)
	at kala.collection@0.73.0/kala.collection.immutable.ImmutableVectors$Vector1.forEach(Unknown Source)
	at aya.cli.impl/org.aya.cli.literate.SyntaxHighlight.highlight(Unknown Source)
	at aya.ide.lsp/org.aya.lsp.actions.SemanticHighlight.highlightOne(Unknown Source)
	at aya.ide.lsp/org.aya.lsp.actions.SemanticHighlight.lambda$highlight$0(Unknown Source)
	at kala.collection@0.73.0/kala.collection.IndexedSeqLike.forEach(Unknown Source)
	at kala.collection@0.73.0/kala.collection.internal.view.CollectionViews$Of.forEach(Unknown Source)
	at aya.ide.lsp/org.aya.lsp.actions.SemanticHighlight.highlight(Unknown Source)
```

**Comment by ice1000** [comment]
Added a message so we can pay attention next time
