### ISSUE TITLE
Illegal char `<:>` at index 0: :theKid

### ISSUE THREAD

**Issue by xianglic** [aya-prover/aya-dev#1143]
```
Aya 0.34.0-SNAPSHOT (55cdeb6e48dba8988c2c092250604625547336d0)
λ> :{
| module C {
|   module A {
|     def f => 1
|   }
| }
| :}
java.nio.file.InvalidPathException: Illegal char <:> at index 0: :theKid
        at java.base/sun.nio.fs.WindowsPathParser.normalize(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPathParser.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsPath.parse(Unknown Source)
        at java.base/sun.nio.fs.WindowsFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.resolve(Unknown Source)
        at kala.collection@0.74.0/kala.collection.IndexedSeqLike.foldLeft(Unknown Source)
        at aya.util/org.aya.util.FileUtil.resolveFile(Unknown Source)
        at aya.syntax/org.aya.syntax.AyaFiles.resolveAyaSourceFile(Unknown Source)
        at aya.base/org.aya.resolve.module.FileModuleLoader.existsFileLevelModule(Unknown Source)
        at aya.base/org.aya.resolve.module.ModuleListLoader.lambda$existsFileLevelModule$0(Unknown Source)
        at kala.collection@0.74.0/kala.collection.IndexedSeqLike.anyMatch(Unknown Source)
```

**Comment by xianglic** [comment]
https://github.com/aya-prover/aya-dev/blob/55cdeb6e48dba8988c2c092250604625547336d0/cli-impl/src/main/java/org/aya/cli/interactive/ReplContext.java#L83

OMG
