### ISSUE TITLE
No such element exception on classes

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#1198]
![image](https://github.com/user-attachments/assets/863ed48c-88f7-4236-aece-4f294170699f)

```
> open class Ok | A : Type
class Ok | A {self : Ok} : Type 0
> A
```

**Comment by ice1000** [comment]
```
> (new Ok Nat).A
java.lang.UnsupportedOperationException: TODO
        at aya.base/org.aya.tyck.ExprTycker.lambda$doSynthesize$17(Unknown Source)
        at kala.base@0.76.0/kala.control.Either.fold(Unknown Source)
        at aya.base/org.aya.tyck.ExprTycker.doSynthesize(Unknown Source)
        at aya.base/org.aya.tyck.ExprTycker.synthesize(Unknown Source)
```
