### ISSUE TITLE
The REPL doesn't handle errors well

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#149]
```
> java --enable-preview -jar .\cli\build\libs\cli-0.11-fat.jar -i
Aya 0.11 (351697c44ce10e377dd91fdd0677f4ceeadfd840)
>open data Empty
data Empty : Type

>def anyway
In file stdin:1:0 ->

  1 | def anyway
      ^--------^

Error: Unsolved meta _4

def anyway : <_4>

>def inconsistency : Empty => anyway
In file stdin:1:0 ->

  1 | def anyway
      ^--------^

Error: Unsolved meta _4

def anyway : <_4>

data Empty : Type

>:t inconsistency
java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at org.aya.core.def.Def.defLevels(Def.java:44)
        at org.aya.tyck.ExprTycker.levelStuffs(ExprTycker.java:519)
        at org.aya.tyck.ExprTycker.defCall(ExprTycker.java:507)
        at org.aya.tyck.ExprTycker.inferRef(ExprTycker.java:477)
        at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:77)
        at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:425)
        at org.aya.concrete.resolve.module.FileModuleLoader.tyckExpr(FileModuleLoader.java:119)
        at org.aya.cli.repl.ReplCompiler.compileExpr(ReplCompiler.java:87)
        at org.aya.cli.repl.ReplCommands$2.execute(ReplCommands.java:32)
        at org.aya.cli.repl.command.CommandManager$CommandGen.invoke(CommandManager.java:24)
        at org.aya.cli.repl.command.CommandManager$Clue.run(CommandManager.java:69)
        at org.aya.cli.repl.Repl.singleLoop(Repl.java:116)
        at org.aya.cli.repl.Repl.run(Repl.java:95)
        at org.aya.cli.repl.Repl.start(Repl.java:32)
        at org.aya.cli.Main.call(Main.java:34)
        at org.aya.cli.Main.call(Main.java:25)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.aya.cli.Main.main(Main.java:27)

>:q
See you space cow woof woof :3
```

LMFAO

**Comment by ice1000** [comment]
There are two problems:

0. The code shouldn't panic
1. Same error is printed twice

**Comment by imkiva** [comment]
Another fun fact: Type `\` then `"` will make REPL dance

**Comment by ice1000** [comment]
> Another fun fact: Typing `\` then `"` will make REPL dance

This is definitely a serious bug 🤣🤣🤣
