### ISSUE TITLE
MetaPat bug?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#271]
```aya
def infix !! (l : List A) (i : Fin (length l)) : A
| a cons l, fzero => a
| a cons l, fsuc i => l !! i
```

Works but

```aya
def infix !! (l : List A) (i : Fin (length l)) : A
| a cons _, fzero => a
| a cons l, fsuc i => l !! i
```

is rejected for the following reason

![image](https://user-images.githubusercontent.com/16398479/145166295-22d74b64-df1f-4839-bbe4-ed0b3f356c2e.png)

**Comment by ice1000** [comment]
Also the pattern pp is not doing a gj

**Comment by ice1000** [comment]
```
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'localCtx' of org/aya/core/pat/Pat$Ctor.rename must not be null
	at org.aya/org.aya.core.pat.Pat$Ctor.$$$reportNull$$$0(Pat.java)
	at org.aya/org.aya.core.pat.Pat$Ctor.rename(Pat.java)
	at org.aya/org.aya.core.pat.PatMatcher.solve(PatMatcher.java:102)
	at org.aya/org.aya.core.pat.PatMatcher.match(PatMatcher.java:77)
	at org.aya/org.aya.core.pat.PatMatcher.match(PatMatcher.java:111)
	at org.aya/org.aya.core.pat.PatMatcher.tryBuildSubstTerms(PatMatcher.java:49)
	at org.aya/org.aya.core.pat.PatMatcher.tryBuildSubstArgs(PatMatcher.java:39)
	at org.aya/org.aya.core.visitor.Unfolder.tryUnfoldClauses(Unfolder.java:118)
	at org.aya/org.aya.core.visitor.Unfolder.tryUnfoldClauses(Unfolder.java:108)
	at org.aya/org.aya.core.visitor.Unfolder.visitFnCall(Unfolder.java:77)
	at org.aya/org.aya.core.visitor.Unfolder.visitFnCall(Unfolder.java:33)
	at org.aya/org.aya.core.term.CallTerm$Fn.doAccept(CallTerm.java:58)
	at org.aya/org.aya.core.term.Term.accept(Term.java:44)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitArg(TermFixpoint.java:108)
	at org.aya/org.aya.core.visitor.Unfolder.lambda$visitConCall$1(Unfolder.java:48)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.map(ImmutableVectors.java:349)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.map(ImmutableVectors.java:161)
	at org.aya/org.aya.core.visitor.Unfolder.visitConCall(Unfolder.java:48)
	at org.aya/org.aya.core.visitor.Unfolder.visitConCall(Unfolder.java:33)
	at org.aya/org.aya.core.term.CallTerm$Con.doAccept(CallTerm.java:140)
	at org.aya/org.aya.core.term.Term.accept(Term.java:44)
	at org.aya/org.aya.core.visitor.Unfolder.tryUnfoldClauses(Unfolder.java:121)
	at org.aya/org.aya.core.visitor.Unfolder.tryUnfoldClauses(Unfolder.java:108)
	at org.aya/org.aya.core.visitor.Unfolder.visitFnCall(Unfolder.java:77)
	at org.aya/org.aya.core.visitor.Unfolder.visitFnCall(Unfolder.java:33)
	at org.aya/org.aya.core.term.CallTerm$Fn.doAccept(CallTerm.java:58)
	at org.aya/org.aya.core.term.Term.accept(Term.java:44)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitArg(TermFixpoint.java:108)
	at org.aya/org.aya.core.visitor.TermFixpoint.lambda$visitDataCall$2(TermFixpoint.java:33)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.map(ImmutableVectors.java:349)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.map(ImmutableVectors.java:161)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitDataCall(TermFixpoint.java:33)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitDataCall(TermFixpoint.java:18)
	at org.aya/org.aya.core.term.CallTerm$Data.doAccept(CallTerm.java:85)
	at org.aya/org.aya.core.term.Term.accept(Term.java:44)
	at org.aya/org.aya.core.term.Term.normalize(Term.java:84)
	at org.aya/org.aya.tyck.pat.PatTycker.selectCtor(PatTycker.java:332)
	at org.aya/org.aya.tyck.pat.PatTycker.doTyck(PatTycker.java:172)
	at org.aya/org.aya.tyck.pat.PatTycker.updateSig(PatTycker.java:290)
	at org.aya/org.aya.tyck.pat.PatTycker.visitPatterns(PatTycker.java:275)
	at org.aya/org.aya.tyck.pat.PatTycker.checkLhs(PatTycker.java:233)
	at org.aya/org.aya.tyck.pat.PatTycker.lambda$checkAllLhs$2(PatTycker.java:119)
	at org.aya/org.aya.tyck.pat.PatTycker.traced(PatTycker.java:73)
	at org.aya/org.aya.tyck.pat.PatTycker.lambda$checkAllLhs$3(PatTycker.java:117)
	at kala.collection/kala.collection.immutable.ImmutableSeqs$Seq2.mapIndexed(ImmutableSeqs.java:446)
	at org.aya/org.aya.tyck.pat.PatTycker.checkAllLhs(PatTycker.java:117)
	at org.aya/org.aya.tyck.pat.PatTycker.elabClausesClassified(PatTycker.java:105)
	at org.aya/org.aya.tyck.StmtTycker.lambda$doTyck$3(StmtTycker.java:99)
	at kala.base/kala.control.Either$Right.fold(Either.java:332)
	at org.aya/org.aya.tyck.StmtTycker.doTyck(StmtTycker.java:78)
```

🤔 🤔 🤔
