### ISSUE TITLE
Jlinked Aya is unable to create a system terminal

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#295]
Forcing it to create one results in the following error:

```
java.lang.IllegalStateException: Unable to create a system terminal
        at org.aya.prover.merged.module@0.14/org.jline.terminal.TerminalBuilder.doBuild(Unknown Source)
        at org.aya.prover.merged.module@0.14/org.jline.terminal.TerminalBuilder.build(Unknown Source)
        at org.aya.cli/org.aya.cli.repl.jline.JlineRepl.<init>(Unknown Source)
        at org.aya.cli/org.aya.cli.repl.AyaRepl.makeRepl(Unknown Source)
        at org.aya.cli/org.aya.cli.repl.AyaRepl.start(Unknown Source)
        at org.aya.cli/org.aya.cli.Main.call(Unknown Source)
        at org.aya.cli/org.aya.cli.Main.call(Unknown Source)
        at info.picocli/picocli.CommandLine.executeUserObject(Unknown Source)
        at info.picocli/picocli.CommandLine.access$1300(Unknown Source)
        at info.picocli/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(Unknown Source)
        at info.picocli/picocli.CommandLine$RunLast.handle(Unknown Source)
        at info.picocli/picocli.CommandLine$RunLast.handle(Unknown Source)
        at info.picocli/picocli.CommandLine$AbstractParseResultHandler.execute(Unknown Source)
        at info.picocli/picocli.CommandLine$RunLast.execute(Unknown Source)
        at info.picocli/picocli.CommandLine.execute(Unknown Source)
        at org.aya.cli/org.aya.cli.Main.main(Unknown Source)
```

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/146642810-a3f888e2-9ab8-4d93-9d50-11a592c69641.png)
![image](https://user-images.githubusercontent.com/16398479/146642817-40cf49f6-dbad-4509-9442-10d017815802.png)

What the

**Comment by ice1000** [comment]
```
Dec 18, 2021 9:03:18 AM org.jline.utils.Log logr
警告: input is tty: false
Dec 18, 2021 9:03:18 AM org.jline.utils.Log logr
警告: output is tty: false
Dec 18, 2021 9:03:18 AM org.jline.utils.Log logr
警告: Creating a dumb terminal
java.lang.IllegalStateException: Unable to create a system terminal
        at org.aya.prover.merged.module@0.14/org.jline.terminal.TerminalBuilder.doBuild(TerminalBuilder.java:329)
        at org.aya.prover.merged.module@0.14/org.jline.terminal.TerminalBuilder.build(TerminalBuilder.java:271)
```

**Comment by ice1000** [comment]
Status: updating the jlink task with the following information

```kotlin
mergedModule {
  val jansi = "org.jline.terminal.spi.JansiSupport"
  uses(jansi)
  provides(jansi).with("org.jline.terminal.impl.jansi.JansiSupportImpl")
}
```

Now the error becomes

```
Exception in thread "main" java.lang.IllegalAccessError: class org.jline.utils.StyleResolver (in module org.aya.prover.merged.module) cannot access class java.util.logging.Logger (in module java.logging) because module org.aya.prover.merged.module does not read module java.logging
        at org.aya.prover.merged.module@0.14/org.jline.utils.StyleResolver.<clinit>(Unknown Source)
        at org.aya.prover.merged.module@0.14/org.jline.builtins.Styles.style(Unknown Source)
        at org.aya.prover.merged.module@0.14/org.jline.builtins.Styles.style(Unknown Source)
        at org.aya.prover.merged.module@0.14/org.jline.builtins.Styles.lsStyle(Unknown Source)
        at org.aya.prover.merged.module@0.14/org.jline.builtins.Completers$FileNameCompleter.<clinit>(Unknown Source)
```

Looks like an easily solvable one

**Comment by ice1000** [comment]
https://badass-jlink-plugin.beryx.org/releases/latest/ is very helpful

**Comment by ice1000** [comment]
Ok I've managed to fix it
