### ISSUE TITLE
NPE in `invokeHover`

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#299]
```
Caused by: java.lang.NullPointerException: Cannot invoke "org.aya.core.def.Def.telescope()" because "core" is null
	at org.aya.lsp.actions.ComputeSignature.computeSignature(ComputeSignature.java:40)
	at org.aya.lsp.actions.ComputeSignature.computeSignature(ComputeSignature.java:32)
	at org.aya.lsp.actions.ComputeSignature.invokeHover(ComputeSignature.java:26)
	at org.aya.lsp.server.AyaService.lambda$hover$20(AyaService.java:277)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```

**Comment by imkiva** [comment]
I guess this is because trying to hover on a term before `C-l C-l` ?

**Comment by ice1000** [comment]
> I guess this is because trying to hover on a term before `C-l C-l` ?

I modified the code while I was hovering

**Comment by imkiva** [comment]
> > I guess this is because trying to hover on a term before `C-l C-l` ?
> 
> I modified the code while I was hovering

How? The hover dismisses when I try to modify the code

**Comment by imkiva** [comment]
fixed in my local head

**Comment by ice1000** [comment]
> > > I guess this is because trying to hover on a term before `C-l C-l` ?
> > 
> > I modified the code while I was hovering
> 
> How? The hover dismisses when I try to modify the code

I don't know, it's very mysterious
