### ISSUE TITLE
NPE in `ReferringResolver.visitProj`

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#303]
```
Caused by: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at org.aya.lsp.utils.Resolver$ReferringResolver.visitProj(Resolver.java:115)
	at org.aya.lsp.utils.Resolver$ReferringResolver.visitProj(Resolver.java:100)
	at org.aya.concrete.Expr$ProjExpr.doAccept(Expr.java:315)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.ExprConsumer.lambda$visitBinOpSeq$0(ExprConsumer.java:30)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:418)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:30)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:10)
	at org.aya.concrete.Expr$BinOpSeq.doAccept(Expr.java:372)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.ExprConsumer.lambda$visitBinOpSeq$0(ExprConsumer.java:30)
	at kala.collection.IndexedSeqLike.forEach(IndexedSeqLike.java:1028)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:30)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:10)
	at org.aya.concrete.Expr$BinOpSeq.doAccept(Expr.java:372)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.ExprConsumer.lambda$visitBinOpSeq$0(ExprConsumer.java:30)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:418)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:30)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:10)
	at org.aya.concrete.Expr$BinOpSeq.doAccept(Expr.java:372)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.ExprConsumer.visitLam(ExprConsumer.java:67)
	at org.aya.concrete.visitor.ExprConsumer.visitLam(ExprConsumer.java:10)
	at org.aya.concrete.Expr$LamExpr.doAccept(Expr.java:214)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.ExprConsumer.lambda$visitBinOpSeq$0(ExprConsumer.java:30)
	at kala.collection.IndexedSeqLike.forEach(IndexedSeqLike.java:1028)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:30)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:10)
	at org.aya.concrete.Expr$BinOpSeq.doAccept(Expr.java:372)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.ExprConsumer.lambda$visitBinOpSeq$0(ExprConsumer.java:30)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:418)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:30)
	at org.aya.concrete.visitor.ExprConsumer.visitBinOpSeq(ExprConsumer.java:10)
	at org.aya.concrete.Expr$BinOpSeq.doAccept(Expr.java:372)
	at org.aya.concrete.Expr.accept(Expr.java:47)
	at org.aya.concrete.visitor.StmtConsumer.visitDecl(StmtConsumer.java:24)
	at org.aya.concrete.visitor.StmtConsumer.visitFn(StmtConsumer.java:55)
	at org.aya.concrete.visitor.StmtConsumer.visitFn(StmtConsumer.java:14)
	at org.aya.concrete.stmt.Decl$FnDecl.doAccept(Decl.java:297)
	at org.aya.concrete.stmt.Decl.accept(Decl.java:65)
	at org.aya.concrete.stmt.Decl.accept(Decl.java:60)
	at org.aya.concrete.stmt.Stmt$Visitor.lambda$visitAll$0(Stmt.java:55)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:418)
	at org.aya.concrete.stmt.Stmt$Visitor.visitAll(Stmt.java:55)
	at org.aya.lsp.actions.FindReferences.lambda$resolve$2(FindReferences.java:55)
	at kala.collection.IndexedSeqLike.forEach(IndexedSeqLike.java:1028)
	at kala.collection.internal.view.Views$Of.forEach(Views.java:445)
	at org.aya.lsp.actions.FindReferences.resolve(FindReferences.java:53)
	at org.aya.lsp.actions.FindReferences.lambda$findRefs$0(FindReferences.java:38)
	at kala.collection.base.Traversable.forEach(Traversable.java:682)
	at org.aya.lsp.actions.FindReferences.lambda$findRefs$1(FindReferences.java:38)
	at kala.collection.base.Traversable.forEach(Traversable.java:682)
	at org.aya.lsp.actions.FindReferences.findRefs(FindReferences.java:38)
	at org.aya.lsp.actions.FindReferences.findOccurrences(FindReferences.java:48)
	at org.aya.lsp.server.AyaService.lambda$documentHighlight$26(AyaService.java:317)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 6 more
```

**Comment by imkiva** [comment]
repro?

**Comment by imkiva** [comment]
fixed in my local head

**Comment by ice1000** [comment]
> repro?

It's difficult
