### ISSUE TITLE
IAE

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#304]
Code

```aya
struct Square {A : Pi (i j : I) -> Type}
  {a : A left  left} {b : A left  right}
  {c : A right left} {d : A right right}
  (ab : Path (A left ) a b)
  (cd : Path (A right) c d)
  (ac : Path (\x => A x left ) a c)
  (bd : Path (\x => A x right) b d) : Type
  | at2 (i j : I) : A i j {
    | left,  i => ab.at i
    | right, i => cd.at i
    | i,  left => ac.at i
    | i, right => bd.at i
  }
```

NPE:
```
java.lang.IllegalArgumentException: a
	at org.aya/org.aya.tyck.env.LocalCtx.get(LocalCtx.java:80)
	at org.aya/org.aya.tyck.unify.DefEq.doCompareUntyped(DefEq.java:326)
	at org.aya/org.aya.tyck.unify.DefEq.compareUntyped(DefEq.java:128)
	at org.aya/org.aya.tyck.unify.DefEq.doCompareTyped(DefEq.java:259)
	at org.aya/org.aya.tyck.unify.DefEq.compare(DefEq.java:114)
	at org.aya/org.aya.tyck.unify.DefEq.compare(DefEq.java:101)
	at org.aya/org.aya.tyck.pat.PatClassifier.lambda$confluence$5(PatClassifier.java:111)
```

🤔🤔

**Comment by ice1000** [comment]
Fixed in local branch
