### ISSUE TITLE
The B in the params and the B in the pattern are not the same B

### ISSUE THREAD

**Issue by refparo** [aya-prover/aya-dev#339]
Commit: ccaa7a0

```aya
open data Unit : Type | unit

open struct Wrapped (A : Type) : Type

def test {B : Type} Unit : Wrapped B -> Unit
  | unit => \(x : Wrapped B) => unit
```

All these changes would fix the error:

```aya
def test {B : Type} Unit : Wrapped B -> Unit
  | {B}, unit => \(x : Wrapped B) => unit

def test {B : Type} Unit : Wrapped B -> Unit
  | unit => \x => unit

def test {B : Type} Unit : Wrapped B -> Unit
  => \(x : Wrapped B) => unit
```

**Comment by refparo** [comment]
This change crashes the language server (but not the compiler).

```aya
variable B : Type

def test Unit : Wrapped B -> Unit
  | unit => \(x : Wrapped B) => unit
```

**Comment by ice1000** [comment]
```aya
def test {B : Type} Unit : Wrapped B -> Unit
  | unit => \(x : Wrapped B) => unit
```

What happens if you click `B` in vscode?

**Comment by ice1000** [comment]
**Conjecture.** This is due to the substitution not working for lambda types.

**Comment by ice1000** [comment]
@ice1000 > Conjecture. This is due to the substitution not working for lambda types.

**Comment by ice1000** [comment]
@ice1000 This is not true

**Comment by imkiva** [comment]
> This change crashes the language server (but not the compiler).
> 
> ```
> variable B : Type
> 
> def test Unit : Wrapped B -> Unit
>   | unit => \(x : Wrapped B) => unit
> ```

Stack trace:
<details>
<pre>
java.lang.IllegalArgumentException: B
	at org.aya/org.aya.tyck.env.LocalCtx.get(LocalCtx.java:80)
	at org.aya/org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:71)
	at org.aya/org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:401)
	at org.aya/org.aya.tyck.ExprTycker.doInherit(ExprTycker.java:345)
	at org.aya/org.aya.tyck.ExprTycker.inherit(ExprTycker.java:394)
	at org.aya/org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:231)
	at org.aya/org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:401)
	at org.aya/org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:81)
	at org.aya/org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:401)
	at org.aya/org.aya.tyck.StmtTycker.tyckHeader(StmtTycker.java:140)
	at org.aya/org.aya.tyck.order.AyaSccTycker.checkHeader(AyaSccTycker.java:119)
	at org.aya/org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:112)
	at org.aya/org.aya.tyck.order.AyaSccTycker.checkUnit(AyaSccTycker.java:77)
	at org.aya/org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:55)
	at org.aya.util/org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:418)
	at org.aya/org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:46)
	at org.aya/org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:35)
	at org.aya.cli/org.aya.cli.single.SingleFileCompiler.lambda$compile$3(SingleFileCompiler.java:71)
	at org.aya.cli/org.aya.cli.utils.AyaCompiler.catching(AyaCompiler.java:31)
	at org.aya.cli/org.aya.cli.single.SingleFileCompiler.compile(SingleFileCompiler.java:64)
	at org.aya.cli/org.aya.cli.single.SingleFileCompiler.compile(SingleFileCompiler.java:52)
	at org.aya.cli/org.aya.cli.Main.call(Main.java:56)
	at org.aya.cli/org.aya.cli.Main.call(Main.java:19)
	at info.picocli/picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at info.picocli/picocli.CommandLine.access$1300(CommandLine.java:145)
	at info.picocli/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at info.picocli/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at info.picocli/picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at info.picocli/picocli.CommandLine.execute(CommandLine.java:2078)
	at org.aya.cli/org.aya.cli.Main.main(Main.java:21)

</pre>
</details>

**Comment by ice1000** [comment]
Simpler repro:

```aya
open data Nat | suc Nat | zero
open data NatPred Nat | blah

def mk (a : Nat) : NatPred a => blah
def conjecture {a : Nat} Nat : NatPred a
| b => mk a
```

**Comment by ice1000** [comment]
```
  4 | def mk (a : Nat) : NatPred a => blah
  5 | def conjecture {a : Nat} Nat : NatPred a
  6 | | b => mk a
             ^--^

Error: Cannot check the expression
         mk a
       of type
         NatPred a
       against the type
         NatPred a
       In particular, we failed to unify
         a
       with
         a
```

This is due to a substitution error

**Comment by ice1000** [comment]
I know how to fix this.

**Comment by ice1000** [comment]
> This change crashes the language server (but not the compiler).
> 
> ```
> variable B : Type
> 
> def test Unit : Wrapped B -> Unit
>   | unit => \(x : Wrapped B) => unit
> ```

This is another problem related to generalization. Care to create an issue? I am also curious on how to solve this. This is because we only dealt with generalized variables in the telescope (and we turn them into usages of a prepended parameter), not in the function bodies. So, if you use them in bodies, they won't be substituted. I have some plans to solve this:

0. Perform substitution on bodies as well. This will make the tycker slower when there are no generalized variables used in bodies, which is likely to be true.
1. Do not allow generalized variables to be used in bodies. This can simplify the implementation, but some code won't work.

**Comment by ice1000** [comment]
@refparo any idea

**Comment by refparo** [comment]
> @refparo any idea

Can we turn them into prepended parameter and then simply proceed as if they were actually parameters?

**Comment by ice1000** [comment]
> > @refparo any idea
> 
> Can we turn them into prepended parameter and then simply proceed as if they were actually parameters?

The thing is that they're first resolved as references to a global thing, and then replaced with references of a freshly generated variable. Did you mean to do the replacement in the whole function body?

**Comment by refparo** [comment]
Oh, I understand now.

Yes, I mean to do the replacement in the whole function body. If we were to disallow generalized variables used in bodies, we would have to look through the body for any used generalized variables to provide better error reporting anyway (I think).
