### ISSUE TITLE
`def a a` triggers NPE

### ISSUE THREAD

**Issue by lunalunaa** [aya-prover/aya-dev#381]
As titled.

Should be something related to resolver.

Stacktrace here
```
java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:208)
	at org.aya/org.aya.core.def.Def.defTele(Def.java:33)
	at org.aya/org.aya.tyck.ExprTycker.defCall(ExprTycker.java:466)
	at org.aya/org.aya.tyck.ExprTycker.inferRef(ExprTycker.java:437)
	at org.aya/org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:67)
	at org.aya/org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:397)
	at org.aya/org.aya.tyck.StmtTycker.lambda$checkTele$10(StmtTycker.java:299)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.map(ImmutableVectors.java:371)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.map(ImmutableVectors.java:162)
	at org.aya/org.aya.tyck.StmtTycker.checkTele(StmtTycker.java:296)
	at org.aya/org.aya.tyck.StmtTycker.tele(StmtTycker.java:284)
	at org.aya/org.aya.tyck.StmtTycker.tyckHeader(StmtTycker.java:136)
	at org.aya/org.aya.tyck.StmtTycker.doTyck(StmtTycker.java:65)
	at org.aya/org.aya.tyck.StmtTycker.traced(StmtTycker.java:54)
	at org.aya/org.aya.tyck.StmtTycker.tyck(StmtTycker.java:61)
	at org.aya/org.aya.tyck.order.AyaSccTycker.checkBody(AyaSccTycker.java:133)
	at org.aya/org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:117)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at org.aya/org.aya.tyck.order.AyaSccTycker.checkMutual(AyaSccTycker.java:73)
	at org.aya/org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:60)
	at org.aya.util/org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at org.aya/org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:39)
	at org.aya/org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:29)
	at org.aya.cli/org.aya.cli.single.SingleFileCompiler.lambda$compile$3(SingleFileCompiler.java:71)
	at org.aya.cli/org.aya.cli.utils.AyaCompiler.catching(AyaCompiler.java:31)
	at org.aya.cli/org.aya.cli.single.SingleFileCompiler.compile(SingleFileCompiler.java:64)
	at org.aya.cli/org.aya.cli.single.SingleFileCompiler.compile(SingleFileCompiler.java:52)
	at org.aya.cli/org.aya.cli.Main.call(Main.java:56)
	at org.aya.cli/org.aya.cli.Main.call(Main.java:19)
	at info.picocli/picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at info.picocli/picocli.CommandLine.access$1300(CommandLine.java:145)
	at info.picocli/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at info.picocli/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at info.picocli/picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at info.picocli/picocli.CommandLine.execute(CommandLine.java:2078)
	at org.aya.cli/org.aya.cli.Main.main(Main.java:21)
```

**Comment by imkiva** [comment]
This should be reported by `AyaSccTycker`, so it's probably a tyck-order bug

**Comment by lunalunaa** [comment]
Another example: in REPL, try `data Nat = ` followed by `Nat`.

`Nat` somehow is resolved into a `Def` even after a tyck error

**Comment by lunalunaa** [comment]
The culprit at REPL should be this one. The context is not properly cleaned up after catching exception.

https://github.com/aya-prover/aya-dev/blob/93bb0ba1d8cd96e5c79c67fc23a1b14b5516d73f/cli/src/main/java/org/aya/cli/repl/ReplCompiler.java#L143-L145

**Comment by lunalunaa** [comment]
> The culprit at REPL should be this one. The context is not properly cleaned up after catching exception.
> 
> https://github.com/aya-prover/aya-dev/blob/93bb0ba1d8cd96e5c79c67fc23a1b14b5516d73f/cli/src/main/java/org/aya/cli/repl/ReplCompiler.java#L143-L145

Opening a new issue for this one.

**Comment by imkiva** [comment]
I think is is also related to #328. Function without a body should also be handled in `AyaSccTycker`

**Comment by ice1000** [comment]
Fixed by #383

**Comment by lunalunaa** [comment]
This does not seem to be fixed in REPL

**Comment by imkiva** [comment]
> This does not seem to be fixed in REPL

![image](https://user-images.githubusercontent.com/9902643/164882923-5fea1d69-ae34-4103-b39e-c2f1f2059a54.png)

How?

**Comment by lunalunaa** [comment]
<img width="667" alt="image" src="https://user-images.githubusercontent.com/26627218/164887093-fded5961-41d5-4aff-b6d7-cf84382ee0ef.png">

**Comment by lunalunaa** [comment]
Well I guess it's probably more appropriate for #382

**Comment by ice1000** [comment]
> The error is reported but the bad context is not cleaned up:
> 
> <img width="838" alt="image" src="https://user-images.githubusercontent.com/26627218/164887207-70f695a5-aef7-441d-853f-47b6593ba124.png">

😱
