### ISSUE TITLE
LSP crashes?

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#458]
```
����: Internal error: java.lang.IllegalArgumentException: object is not an instance of declaring class
java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.checkReceiver(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.aya.prover.merged.module@0.20-SNAPSHOT/org.eclipse.lsp4j.jsonrpc.services.EndpointProxy.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy10.clearAyaProblems(Unknown Source)
	at aya.lsp/org.aya.lsp.server.AyaService.clearProblems(Unknown Source)
	at aya.lsp/org.aya.lsp.server.AyaService$CallbackAdvisor.notifyIncrementalJob(Unknown Source)
	at aya.cli/org.aya.cli.library.LibraryCompiler.make(Unknown Source)
	at aya.cli/org.aya.cli.library.LibraryCompiler.make(Unknown Source)
	at aya.cli/org.aya.cli.library.LibraryCompiler.make(Unknown Source)
	at aya.cli/org.aya.cli.utils.AyaCompiler.catching(Unknown Source)
	at aya.cli/org.aya.cli.library.LibraryCompiler.start(Unknown Source)
	at aya.lsp/org.aya.lsp.server.AyaService.loadLibrary(Unknown Source)
	at kala.collection/kala.collection.internal.view.SeqViews$FlatMapped.lambda$iterator$0(Unknown Source)
	at kala.base/kala.collection.base.Iterators$3.next(Unknown Source)
	at kala.base/kala.collection.base.Iterators$ConcatAll.hasNext(Unknown Source)
	at kala.collection/kala.collection.immutable.ImmutableVector.from(Unknown Source)
	at kala.collection/kala.collection.immutable.ImmutableVector.from(Unknown Source)
```

@imkiva save me save me

**Comment by ice1000** [comment]
Oh geez I was using 0.19 lsp

**Comment by ice1000** [comment]
```
D:\git-repos\aya-prover\lsp\build\libs\lsp-0.20-SNAPSHOT.jar��û�����嵥����
The language server exited with 1 (null)
```

**Comment by ice1000** [comment]
Wut

**Comment by ice1000** [comment]
These error messages are not very helpful! I used the thin jar and it just crashes me

**Comment by ice1000** [comment]
```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:67)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.notify(GenericEndpoint.java:152)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleNotification(RemoteEndpoint.java:220)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:187)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:119)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.eclipse.lsp4j.jsonrpc.services.GenericEndpoint.lambda$null$0(GenericEndpoint.java:65)
	... 11 more
Caused by: java.lang.UnsupportedOperationException
	at org.eclipse.lsp4j.services.LanguageServer.setTrace(LanguageServer.java:115)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 13 more
```
