### ISSUE TITLE
InternalException when using '_' in pattern matching

### ISSUE THREAD

**Issue by HoshinoTented** [aya-prover/aya-dev#495]
Aya Version: `Aya 0.21-SNAPSHOT (cd83ede22d1313392c11a2aa1e826e65dd495559)`
OS: `Windows 11`
JRE: `openjdk 18.0.2.1 2022-08-18`

code: 

```
open data Unit 
  | unit

def bad (u : Unit)
  | _ => u
```

error message:
<details>
<summary>org.aya.generic.util.InternalException: _</summary>

```
org.aya.generic.util.InternalException: _
        at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:85)
        at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:68)
        at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:569)
        at org.aya.tyck.ExprTycker.doInherit(ExprTycker.java:471)
        at org.aya.tyck.ExprTycker.inherit(ExprTycker.java:562)
        at org.aya.tyck.pat.PatTycker.lambda$checkRhs$9(PatTycker.java:246)
        at kala.control.Option.map(Option.java:159)
        at org.aya.tyck.pat.PatTycker.checkRhs(PatTycker.java:240)
        at org.aya.tyck.pat.PatTycker.lambda$checkAllRhs$5(PatTycker.java:144)
        at org.aya.tyck.pat.PatTycker.traced(PatTycker.java:78)
        at org.aya.tyck.pat.PatTycker.lambda$checkAllRhs$6(PatTycker.java:142)
        at kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:408)
        at kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:162)
        at org.aya.tyck.pat.PatTycker.checkAllRhs(PatTycker.java:142)
        at org.aya.tyck.pat.PatTycker.elabClausesClassified(PatTycker.java:128)
        at org.aya.tyck.StmtTycker.lambda$doTyck$3(StmtTycker.java:95)
        at kala.control.Either$Right.fold(Either.java:332)
        at org.aya.tyck.StmtTycker.doTyck(StmtTycker.java:75)
        at org.aya.tyck.StmtTycker.traced(StmtTycker.java:56)
        at org.aya.tyck.StmtTycker.tyck(StmtTycker.java:63)
        at org.aya.tyck.order.AyaSccTycker.checkBody(AyaSccTycker.java:172)
        at org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:160)
        at org.aya.tyck.order.AyaSccTycker.checkUnit(AyaSccTycker.java:124)
        at org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:64)
        at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
        at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
        at org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:41)
        at org.aya.cli.repl.ReplCompiler.lambda$compileToContext$6(ReplCompiler.java:130)
        at kala.control.Either$Left.map(Either.java:166)
        at org.aya.cli.repl.ReplCompiler.compileToContext(ReplCompiler.java:125)
        at org.aya.cli.repl.AyaRepl.eval(AyaRepl.java:106)
        at org.aya.repl.Repl.loop(Repl.java:29)
        at org.aya.cli.repl.AyaRepl.singleLoop(AyaRepl.java:102)
        at org.aya.cli.repl.AyaRepl.run(AyaRepl.java:91)
        at org.aya.cli.repl.AyaRepl.start(AyaRepl.java:28)
        at org.aya.cli.Main.call(Main.java:32)
        at org.aya.cli.Main.call(Main.java:21)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at org.aya.cli.Main.main(Main.java:23)
```

</details>

I only tested in REPL, but I think this doesn't matter.

**Comment by ice1000** [comment]
😱
