### ISSUE TITLE
LSP TODO

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#504]
```
9�� 16, 2022 9:50:57 ���� org.eclipse.lsp4j.jsonrpc.RemoteEndpoint fallbackResponseError
����: Internal error: java.lang.UnsupportedOperationException: TODO
java.util.concurrent.CompletionException: java.lang.UnsupportedOperationException: TODO
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.UnsupportedOperationException: TODO
	at org.aya.tyck.unify.DefEq.doCompareTyped(DefEq.java:305)
	at org.aya.tyck.unify.DefEq.compare(DefEq.java:122)
	at org.aya.tyck.unify.DefEq.doCompareUntyped(DefEq.java:370)
	at org.aya.tyck.unify.DefEq.compareUntyped(DefEq.java:136)
	at org.aya.tyck.unify.DefEq.compare(DefEq.java:120)
	at org.aya.tyck.unify.DefEq.compare(DefEq.java:109)
	at org.aya.tyck.ExprTycker.unifyTy(ExprTycker.java:657)
	at org.aya.tyck.ExprTycker.unifyTyMaybeInsert(ExprTycker.java:691)
	at org.aya.tyck.ExprTycker.doInherit(ExprTycker.java:463)
	at org.aya.tyck.ExprTycker.inherit(ExprTycker.java:543)
	at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:190)
	at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:550)
	at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:160)
	at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:550)
	at org.aya.tyck.ExprTycker.doInherit(ExprTycker.java:463)
	at org.aya.tyck.ExprTycker.inherit(ExprTycker.java:543)
	at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:190)
	at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:550)
	at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:160)
	at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:550)
	at org.aya.tyck.StmtTycker.tyckHeader(StmtTycker.java:184)
	at org.aya.tyck.order.AyaSccTycker.checkHeader(AyaSccTycker.java:165)
	at org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:159)
	at org.aya.tyck.order.AyaSccTycker.checkUnit(AyaSccTycker.java:124)
	at org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:64)
	at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:26)
	at kala.collection.immutable.ImmutableVectors.forEachRec(ImmutableVectors.java:745)
	at kala.collection.immutable.ImmutableVectors$BigVector.forEach(ImmutableVectors.java:567)
	at org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:41)
	at org.aya.cli.library.LibraryModuleLoader.load(LibraryModuleLoader.java:79)
	at org.aya.resolve.module.CachedModuleLoader.lambda$load$0(CachedModuleLoader.java:32)
	at kala.collection.mutable.MutableTreeMap.getOrPut(MutableTreeMap.java:483)
	at org.aya.resolve.module.CachedModuleLoader.load(CachedModuleLoader.java:32)
	at org.aya.resolve.module.ModuleLoader.load(ModuleLoader.java:63)
	at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckOne(LibraryCompiler.java:316)
	at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckSCC(LibraryCompiler.java:305)
	at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.function.CheckedConsumer.accept(CheckedConsumer.java:46)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at kala.collection.base.Traversable.forEachChecked(Traversable.java:684)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:209)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:179)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:158)
	at org.aya.cli.utils.AyaCompiler.catching(AyaCompiler.java:30)
	at org.aya.cli.library.LibraryCompiler.start(LibraryCompiler.java:144)
	at org.aya.lsp.server.AyaService.loadLibrary(AyaService.java:155)
	at kala.collection.internal.view.SeqViews$FlatMapped.lambda$iterator$0(SeqViews.java:1142)
	at kala.collection.base.Iterators$3.next(Iterators.java:748)
	at kala.collection.base.Iterators$ConcatAll.hasNext(Iterators.java:2056)
	at kala.collection.immutable.ImmutableVector.from(ImmutableVector.java:154)
	at kala.collection.immutable.ImmutableVector.from(ImmutableVector.java:139)
	at kala.collection.CollectionLike.toImmutableVector(CollectionLike.java:104)
	at kala.collection.CollectionLike.toImmutableSeq(CollectionLike.java:92)
	at org.aya.lsp.server.AyaService.reload(AyaService.java:146)
	at org.aya.lsp.server.AyaServer.lambda$load$0(AyaServer.java:37)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
```

**Comment by ice1000** [comment]
Oh

**Comment by ice1000** [comment]
Should be fixed by #505
