### ISSUE TITLE
InternalException when using `as`

### ISSUE THREAD

**Issue by HoshinoTented** [aya-prover/aya-dev#595]
Aya Version: `Aya 0.23-SNAPSHOT (4406fe4e96b75628857b3ff7347d55d387bf8523)`
OS: `Windows 11`
JRE: `liberica jdk 19`

Code:
```aya
open data Nat | O | S Nat
def what (n : Nat) : Nat | (O) as o => o | (S n) as sn => sn
```

<details>
<summary>Aya said:</summary>

```
In file <stdin>:1:28 ->

  1 | def what (n : Nat) : Nat | (O) as o => o | (S n) as sn => sn
                                  ^^

Warning: The name `o' shadows a previous local definition from outer scope

In file <stdin>:1:44 ->

  1 | def what (n : Nat) : Nat | (O) as o => o | (S n) as sn => sn
                                                  ^-^

Warning: The name `sn' shadows a previous local definition from outer scope

org.aya.generic.util.InternalException: o
	at aya.base/org.aya.tyck.env.LocalCtx.get(LocalCtx.java:101)
	at aya.base/org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:65)
	at aya.base/org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:609)
	at aya.base/org.aya.tyck.ExprTycker.doInherit(ExprTycker.java:491)
	at aya.base/org.aya.tyck.ExprTycker.inherit(ExprTycker.java:602)
	at aya.base/org.aya.tyck.pat.PatTycker.lambda$checkRhs$9(PatTycker.java:249)
	at kala.base/kala.control.Option.map(Option.java:159)
	at aya.base/org.aya.tyck.pat.PatTycker.checkRhs(PatTycker.java:243)
	at aya.base/org.aya.tyck.pat.PatTycker.lambda$checkAllRhs$5(PatTycker.java:151)
	at aya.base/org.aya.tyck.pat.PatTycker.traced(PatTycker.java:85)
	at aya.base/org.aya.tyck.pat.PatTycker.lambda$checkAllRhs$6(PatTycker.java:149)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:408)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:162)
	at aya.base/org.aya.tyck.pat.PatTycker.checkAllRhs(PatTycker.java:149)
	at aya.base/org.aya.tyck.pat.PatTycker.elabClausesClassified(PatTycker.java:135)
	at aya.base/org.aya.tyck.StmtTycker.lambda$doTyck$3(StmtTycker.java:94)
	at kala.base/kala.control.Either$Right.fold(Either.java:332)
	at aya.base/org.aya.tyck.StmtTycker.doTyck(StmtTycker.java:74)
	at aya.base/org.aya.tyck.StmtTycker.traced(StmtTycker.java:55)
	at aya.base/org.aya.tyck.StmtTycker.tyck(StmtTycker.java:62)
	at aya.base/org.aya.tyck.order.AyaSccTycker.checkBody(AyaSccTycker.java:173)
	at aya.base/org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:161)
	at aya.base/org.aya.tyck.order.AyaSccTycker.checkUnit(AyaSccTycker.java:124)
	at aya.base/org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:64)
	at aya.util/org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at aya.base/org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:41)
	at aya.cli/org.aya.cli.repl.ReplCompiler.lambda$compileToContext$6(ReplCompiler.java:130)
	at kala.base/kala.control.Either$Left.map(Either.java:166)
	at aya.cli/org.aya.cli.repl.ReplCompiler.compileToContext(ReplCompiler.java:125)
	at aya.cli/org.aya.cli.repl.AyaRepl.eval(AyaRepl.java:107)
	at aya.repl/org.aya.repl.Repl.loop(Repl.java:34)
	at aya.cli/org.aya.cli.repl.AyaRepl.singleLoop(AyaRepl.java:103)
	at aya.cli/org.aya.cli.repl.AyaRepl.run(AyaRepl.java:92)
	at aya.cli/org.aya.cli.repl.AyaRepl.start(AyaRepl.java:28)
	at aya.cli/org.aya.cli.Main.call(Main.java:36)
	at aya.cli/org.aya.cli.Main.call(Main.java:25)
	at info.picocli/picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at info.picocli/picocli.CommandLine.access$1300(CommandLine.java:145)
	at info.picocli/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at info.picocli/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at info.picocli/picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at info.picocli/picocli.CommandLine.execute(CommandLine.java:2078)
	at aya.cli/org.aya.cli.Main.main(Main.java:27)
```

</details>

**Comment by ice1000** [comment]
I think the impl of `as` is totally wrong

**Comment by ice1000** [comment]
![image](https://user-images.githubusercontent.com/16398479/203864508-6e944dc3-2079-4499-9b1e-790803f5db75.png)
