### ISSUE TITLE
expected: compiler error, but actual: NoSuchElementException

### ISSUE THREAD

**Issue by HoshinoTented** [aya-prover/aya-dev#597]
Aya Version: `Aya 0.23-SNAPSHOT (4406fe4e96b75628857b3ff7347d55d387bf8523)`

Minimum code:

```aya
open data Nat | O | S Nat
def bad Nat : Nat | S S O => O | _ => O
```

Aya should report a compiler error ( `S (S O)` instead of `S S O` ), but `NoSuchElementException` was thrown.

<details>
<summary>java.util.NoSuchElementException</summary>

```
java.util.NoSuchElementException
	at kala.base/kala.collection.base.Iterators$5.next(Iterators.java:1256)
	at kala.collection/kala.collection.SeqLike.last(SeqLike.java:169)
	at aya.base/org.aya.tyck.pat.PatTycker.visitPatterns(PatTycker.java:276)
	at aya.base/org.aya.tyck.pat.PatTycker.doTyck(PatTycker.java:189)
	at aya.base/org.aya.tyck.pat.PatTycker.updateSig(PatTycker.java:327)
	at aya.base/org.aya.tyck.pat.PatTycker.visitPatterns(PatTycker.java:305)
	at aya.base/org.aya.tyck.pat.PatTycker.doTyck(PatTycker.java:189)
	at aya.base/org.aya.tyck.pat.PatTycker.updateSig(PatTycker.java:327)
	at aya.base/org.aya.tyck.pat.PatTycker.visitPatterns(PatTycker.java:305)
	at aya.base/org.aya.tyck.pat.PatTycker.checkLhs(PatTycker.java:258)
	at aya.base/org.aya.tyck.pat.PatTycker.lambda$checkAllLhs$2(PatTycker.java:142)
	at aya.base/org.aya.tyck.pat.PatTycker.traced(PatTycker.java:85)
	at aya.base/org.aya.tyck.pat.PatTycker.lambda$checkAllLhs$3(PatTycker.java:140)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:408)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.mapIndexed(ImmutableVectors.java:162)
	at aya.base/org.aya.tyck.pat.PatTycker.checkAllLhs(PatTycker.java:140)
	at aya.base/org.aya.tyck.pat.PatTycker.elabClausesClassified(PatTycker.java:126)
	at aya.base/org.aya.tyck.StmtTycker.lambda$doTyck$3(StmtTycker.java:94)
	at kala.base/kala.control.Either$Right.fold(Either.java:332)
	at aya.base/org.aya.tyck.StmtTycker.doTyck(StmtTycker.java:74)
	at aya.base/org.aya.tyck.StmtTycker.traced(StmtTycker.java:55)
	at aya.base/org.aya.tyck.StmtTycker.tyck(StmtTycker.java:62)
	at aya.base/org.aya.tyck.order.AyaSccTycker.checkBody(AyaSccTycker.java:173)
	at aya.base/org.aya.tyck.order.AyaSccTycker.check(AyaSccTycker.java:161)
	at aya.base/org.aya.tyck.order.AyaSccTycker.checkUnit(AyaSccTycker.java:124)
	at aya.base/org.aya.tyck.order.AyaSccTycker.tyckSCC(AyaSccTycker.java:64)
	at aya.util/org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at aya.base/org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:41)
	at aya.cli/org.aya.cli.repl.ReplCompiler.lambda$compileToContext$6(ReplCompiler.java:130)
	at kala.base/kala.control.Either$Left.map(Either.java:166)
	at aya.cli/org.aya.cli.repl.ReplCompiler.compileToContext(ReplCompiler.java:125)
	at aya.cli/org.aya.cli.repl.AyaRepl.eval(AyaRepl.java:107)
	at aya.repl/org.aya.repl.Repl.loop(Repl.java:34)
	at aya.cli/org.aya.cli.repl.AyaRepl.singleLoop(AyaRepl.java:103)
	at aya.cli/org.aya.cli.repl.AyaRepl.run(AyaRepl.java:92)
	at aya.cli/org.aya.cli.repl.AyaRepl.start(AyaRepl.java:28)
	at aya.cli/org.aya.cli.Main.call(Main.java:36)
	at aya.cli/org.aya.cli.Main.call(Main.java:25)
	at info.picocli/picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at info.picocli/picocli.CommandLine.access$1300(CommandLine.java:145)
	at info.picocli/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at info.picocli/picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at info.picocli/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at info.picocli/picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at info.picocli/picocli.CommandLine.execute(CommandLine.java:2078)
	at aya.cli/org.aya.cli.Main.main(Main.java:27)
```

</details>

**Comment by HoshinoTented** [comment]
Maybe a similar problem:

```aya
open data Single (A : Type) | single {A}
open data Unit | unit
def bad (s : Single Unit) : Unit
  | single => unit
```
