### ISSUE TITLE
Two fixl throw exception

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#677]
```aya
data False
def fixl ¬ (A : Type) => A -> False
def NonEmpty (A : Type) => ¬ ¬ A
```

```
Caused by: java.util.NoSuchElementException
	at kala.collection.mutable.MutableLinkedList.removeLast(MutableLinkedList.java:393)
	at kala.collection.mutable.MutableDeque.dequeue(MutableDeque.java:140)
	at org.aya.util.binop.BinOpParser.makeBinApp(BinOpParser.java:144)
	at org.aya.util.binop.BinOpParser.foldTop(BinOpParser.java:138)
	at org.aya.util.binop.BinOpParser.foldLhsFor(BinOpParser.java:132)
	at org.aya.util.binop.BinOpParser.convertToPrefix(BinOpParser.java:85)
	at org.aya.util.binop.BinOpParser.build(BinOpParser.java:53)
	at org.aya.concrete.desugar.Desugarer.pre(Desugarer.java:78)
	at org.aya.concrete.visitor.EndoExpr.apply(EndoExpr.java:25)
	at org.aya.concrete.visitor.EndoExpr.apply(EndoExpr.java:15)
	at kala.control.Either$Left.map(Either.java:166)
	at org.aya.concrete.visitor.StmtConsumer.accept(StmtConsumer.java:25)
	at org.aya.concrete.stmt.Stmt.desugar(Stmt.java:39)
	at org.aya.concrete.stmt.Stmt.lambda$resolve$0(Stmt.java:35)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at org.aya.concrete.stmt.Stmt.resolve(Stmt.java:35)
	at org.aya.resolve.module.ModuleLoader.resolveModule(ModuleLoader.java:56)
	at org.aya.cli.library.LibraryModuleLoader.load(LibraryModuleLoader.java:77)
	at org.aya.resolve.module.CachedModuleLoader.lambda$load$0(CachedModuleLoader.java:32)
	at kala.collection.mutable.MutableTreeMap.getOrPut(MutableTreeMap.java:483)
	at org.aya.resolve.module.CachedModuleLoader.load(CachedModuleLoader.java:32)
	at org.aya.resolve.module.ModuleLoader.load(ModuleLoader.java:63)
	at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckOne(LibraryCompiler.java:323)
	at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckSCC(LibraryCompiler.java:310)
	at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
	at kala.function.CheckedConsumer.accept(CheckedConsumer.java:46)
	at kala.collection.immutable.ImmutableVectors$Vector1.forEach(ImmutableVectors.java:440)
	at kala.collection.base.Traversable.forEachChecked(Traversable.java:706)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:212)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:182)
	at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:161)
	at org.aya.cli.utils.AyaCompiler.catching(AyaCompiler.java:30)
	at org.aya.cli.library.LibraryCompiler.start(LibraryCompiler.java:147)
	at org.aya.lsp.server.AyaLanguageServer.loadLibrary(AyaLanguageServer.java:201)
	at kala.collection.internal.view.SeqViews$FlatMapped.lambda$iterator$0(SeqViews.java:1142)
	at kala.collection.base.Iterators$3.next(Iterators.java:777)
	at kala.collection.base.Iterators$ConcatAll.hasNext(Iterators.java:2116)
	at kala.collection.immutable.ImmutableVector.from(ImmutableVector.java:155)
	at kala.collection.immutable.ImmutableVector.from(ImmutableVector.java:140)
	at kala.collection.CollectionLike.toImmutableVector(CollectionLike.java:107)
	at kala.collection.CollectionLike.toImmutableSeq(CollectionLike.java:95)
	at org.aya.lsp.server.AyaLanguageServer.reload(AyaLanguageServer.java:192)
	at org.aya.lsp.server.AyaLanguageServer.load(AyaLanguageServer.java:373)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	... 13 more
```

**Comment by ice1000** [comment]
Oh I see, this should be `fixr`

**Comment by imkiva** [comment]
At least there should an error, not crashing the compiler
