### ISSUE TITLE
null

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#704]
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:116)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.javacs.lsp.LSP.connect(LSP.java:244)
	at org.aya.lsp.LspMain.call(LspMain.java:35)
	at org.aya.lsp.LspMain.call(LspMain.java:22)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.aya.lsp.LspMain.main(LspMain.java:24)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.Map.entrySet()" because "this.dependency" is null
	at org.aya.cli.library.json.LibraryConfigData.asConfig(LibraryConfigData.java:57)
	at org.aya.cli.library.json.LibraryConfigData.fromDependencyRoot(LibraryConfigData.java:79)
	at org.aya.cli.library.source.DiskLibraryOwner.depConfig(DiskLibraryOwner.java:33)
	at org.aya.cli.library.source.DiskLibraryOwner.from(DiskLibraryOwner.java:49)
	at org.aya.lsp.server.AyaLanguageServer.tryAyaLibrary(AyaLanguageServer.java:89)
	at org.aya.lsp.server.AyaLanguageServer.registerLibrary(AyaLanguageServer.java:80)
	at org.aya.lsp.server.AyaLanguageServer.lambda$initialize$0(AyaLanguageServer.java:137)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.aya.lsp.server.AyaLanguageServer.initialize(AyaLanguageServer.java:136)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
```

**Comment by tsao-chi** [comment]
https://github.com/aya-prover/aya-dev/issues/704

**Comment by imkiva** [comment]
> at org.aya.cli.library.json.LibraryConfigData.asConfig(LibraryConfigData.java:57)

Can you fix?

**Comment by tsao-chi** [comment]
wo kan cuo le

**Comment by tsao-chi** [comment]
I think this NPE is impossible in the latest `main`
