### ISSUE TITLE
Patterns raise error does not prevent bodies from being tycked

### ISSUE THREAD

**Issue by ice1000** [aya-prover/aya-dev#746]
```
def Sphere1-S¹ (Sphere 1) : S¹
| north => base
| south => base
| loop i => loop i
```

Raises:

```
org.aya.generic.util.InternalException: i
i
	at org.aya.tyck.env.LocalCtx.get(LocalCtx.java:104)
	at org.aya.tyck.ExprTycker.lambda$doSynthesize$0(ExprTycker.java:104)
	at kala.control.OptionContainer.getOrElse(OptionContainer.java:106)
	at org.aya.tyck.ExprTycker.doSynthesize(ExprTycker.java:102)
	at org.aya.tyck.ExprTycker.synthesize(ExprTycker.java:700)
```

**Comment by ice1000** [comment]
My fault
