### ISSUE TITLE
Native image bug

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#809]
```
➜ nativeCompile git:(main) .\aya-native-windows-latest_x86-64.exe ..\..\..\..\test.aya
Exception in thread "main" java.lang.ExceptionInInitializerError                                                                                                                                              at com.intellij.lang.parser.GeneratedParserUtilBase$ErrorState.getExpected(GeneratedParserUtilBase.java:857)                                                                                          at com.intellij.lang.parser.GeneratedParserUtilBase.reportError(GeneratedParserUtilBase.java:705)                                                                                                     at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_impl_(GeneratedParserUtilBase.java:527)
        at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_(GeneratedParserUtilBase.java:462)
        at com.intellij.lang.parser.GeneratedParserUtilBase.exit_section_(GeneratedParserUtilBase.java:439)
        at org.aya.parser.AyaPsiParser.stmt_with_recover(AyaPsiParser.java:1718)
        at org.aya.parser.AyaPsiParser.stmts(AyaPsiParser.java:1743)
        at org.aya.parser.AyaPsiParser.program(AyaPsiParser.java:1490)
        at org.aya.parser.AyaPsiParser.parse_root_(AyaPsiParser.java:35)
        at org.aya.parser.AyaPsiParser.parse_root_(AyaPsiParser.java:31)
        at org.aya.parser.AyaPsiParser.parseLight(AyaPsiParser.java:26)
        at com.intellij.psi.FleetPsiParser$DefaultPsiParser.parse(FleetPsiParser.java:62)
        at com.intellij.psi.FleetPsiParser.parse(FleetPsiParser.java:27)
        at com.intellij.psi.FleetPsiParser$DefaultPsiParser.parse(FleetPsiParser.java:66)
        at org.aya.cli.parse.AyaParserImpl.parseNode(AyaParserImpl.java:38)
        at org.aya.cli.parse.AyaParserImpl.parse(AyaParserImpl.java:57)
        at org.aya.cli.parse.AyaParserImpl.program(AyaParserImpl.java:48)
        at org.aya.concrete.GenericAyaFile.parseMe(GenericAyaFile.java:28)
        at org.aya.cli.single.SingleFileCompiler.lambda$compile$3(SingleFileCompiler.java:54)
        at org.aya.cli.utils.AyaCompiler.catching(AyaCompiler.java:30)
        at org.aya.cli.single.SingleFileCompiler.compile(SingleFileCompiler.java:48)
        at org.aya.cli.single.SingleFileCompiler.compile(SingleFileCompiler.java:37)
        at org.aya.cli.Main.doCompile(Main.java:88)
        at org.aya.cli.Main.call(Main.java:44)
        at org.aya.cli.Main.call(Main.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.aya.cli.Main.main(Main.java:31)
Caused by: java.util.MissingResourceException: Can't find bundle for base name messages.AnalysisBundle, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1549)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:858)
        at com.intellij.analysis.AnalysisBundle.<clinit>(AnalysisBundle.java:12)
        ... 34 more
```

**Comment by ice1000** [comment]
😨

**Comment by tsao-chi** [comment]
https://github.com/aya-prover/upstreams/blob/6f51a831fb7c90c07ed38daeed9904d7a447009c/ij-parsing-core/src/main/java/com/intellij/analysis/AnalysisBundle.java#L12

Maybe the native image generator didn't add this resource by default?

**Comment by imkiva** [comment]
> https://github.com/aya-prover/upstreams/blob/6f51a831fb7c90c07ed38daeed9904d7a447009c/ij-parsing-core/src/main/java/com/intellij/analysis/AnalysisBundle.java#L12
> 
> Maybe the native image generator didn't add this resource by default?

I don't know. Maybe we can add it to something on our own (like `reflect-config.json`)

**Comment by ice1000** [comment]
`-H:IncludeResourceBundles=XXXXX`

**Comment by ice1000** [comment]
https://www.graalvm.org/22.1/reference-manual/native-image/Resources/

**Comment by ice1000** [comment]
Anybody would like to try this out and test it?

**Comment by tsao-chi** [comment]
@imkiva What's in test.aya?

**Comment by ice1000** [comment]
> @imkiva What's in test.aya?

I sort of believe that it has to contain a syntax error but I'm not sure

**Comment by imkiva** [comment]
> @imkiva What's in test.aya?

Sorry, I don't remember. My `test.aya` changes very often 😭

**Comment by tsao-chi** [comment]
A test.aya for reproducing this issue:
```
u&683ugi98}||}{"
```

**Comment by tsao-chi** [comment]
Basically any syntax error can trigger this
