### ISSUE TITLE
Another native image bug

### ISSUE THREAD

**Issue by tsao-chi** [aya-prover/aya-dev#821]
```
./cli/build/native/nativeCompile/aya -i
Aya 0.26-SNAPSHOT (29065eaf5572455d2cdd68b09df2f8759e61102d)
> :load base/src/test/resources/success
Compiling common
  [Info] Resolving source file dependency
    Done in 231ms
  [Tyck] Relation::Formula (Relation/Formula.aya)
com.oracle.svm.core.jdk.UnsupportedFeatureError: SerializationConstructorAccessor class not found for declaringClass: kala.function.Hasher$Optimized (targetConstructorClass: java.lang.Object). Usually adding kala.function.Hasher$Optimized to serialization-config.json fixes the problem.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.reflect.serialize.SerializationSupport.getSerializationConstructorAccessor(SerializationSupport.java:143)
        at java.base@17.0.5/jdk.internal.reflect.MethodAccessorGenerator.generateSerializationConstructor(MethodAccessorGenerator.java:48)
        at java.base@17.0.5/jdk.internal.reflect.ReflectionFactory.generateConstructor(ReflectionFactory.java:463)
        at java.base@17.0.5/jdk.internal.reflect.ReflectionFactory.newConstructorForSerialization(ReflectionFactory.java:455)
        at java.base@17.0.5/java.io.ObjectStreamClass.getSerializableConstructor(ObjectStreamClass.java:1443)
        at java.base@17.0.5/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:412)
        at java.base@17.0.5/java.io.ObjectStreamClass$2.run(ObjectStreamClass.java:384)
        at java.base@17.0.5/java.security.AccessController.executePrivileged(AccessController.java:168)
        at java.base@17.0.5/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.base@17.0.5/java.io.ObjectStreamClass.<init>(ObjectStreamClass.java:384)
        at java.base@17.0.5/java.io.ObjectStreamClass$Caches$1.computeValue(ObjectStreamClass.java:110)
        at java.base@17.0.5/java.io.ObjectStreamClass$Caches$1.computeValue(ObjectStreamClass.java:107)
        at java.base@17.0.5/java.io.ClassCache$1.computeValue(ClassCache.java:73)
        at java.base@17.0.5/java.io.ClassCache$1.computeValue(ClassCache.java:70)
        at java.base@17.0.5/java.lang.ClassValue.get(JavaLangSubstitutions.java:590)
        at java.base@17.0.5/java.io.ClassCache.get(ClassCache.java:84)
        at java.base@17.0.5/java.io.ObjectStreamClass.lookup(ObjectStreamClass.java:363)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1137)
        at java.base@17.0.5/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
        at java.base@17.0.5/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1529)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1438)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
        at java.base@17.0.5/java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1572)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeRecordData(ObjectOutputStream.java:1490)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1434)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1181)
        at java.base@17.0.5/java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:350)
        at org.aya.cli.utils.AyaCompiler.saveCompiledCore(AyaCompiler.java:57)
        at org.aya.cli.library.incremental.DiskCompilerAdvisor.doSaveCompiledCore(DiskCompilerAdvisor.java:82)
        at org.aya.cli.library.incremental.CompilerAdvisor.saveCompiledCore(CompilerAdvisor.java:111)
        at org.aya.cli.library.LibraryModuleLoader.saveCompiledCore(LibraryModuleLoader.java:97)
        at org.aya.cli.library.LibraryModuleLoader.lambda$load$0(LibraryModuleLoader.java:81)
        at org.aya.resolve.module.ModuleLoader.tyckModule(ModuleLoader.java:44)
        at org.aya.cli.library.LibraryModuleLoader.load(LibraryModuleLoader.java:79)
        at org.aya.resolve.module.CachedModuleLoader.lambda$load$0(CachedModuleLoader.java:32)
        at kala.collection.mutable.MutableTreeMap.getOrPut(MutableTreeMap.java:483)
        at org.aya.resolve.module.CachedModuleLoader.load(CachedModuleLoader.java:32)
        at org.aya.resolve.module.ModuleLoader.load(ModuleLoader.java:77)
        at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckOne(LibraryCompiler.java:324)
        at org.aya.cli.library.LibraryCompiler$LibrarySccTycker.tyckSCC(LibraryCompiler.java:311)
        at org.aya.util.tyck.OrgaTycker.tyckSCC(OrgaTycker.java:25)
        at kala.function.CheckedConsumer.accept(CheckedConsumer.java:46)
        at kala.collection.immutable.ImmutableVectors.forEachRec(ImmutableVectors.java:745)
        at kala.collection.immutable.ImmutableVectors$BigVector.forEach(ImmutableVectors.java:567)
        at kala.collection.base.Traversable.forEachChecked(Traversable.java:733)
        at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:213)
        at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:183)
        at org.aya.cli.library.LibraryCompiler.make(LibraryCompiler.java:162)
        at org.aya.cli.utils.AyaCompiler.catching(AyaCompiler.java:30)
        at org.aya.cli.library.LibraryCompiler.start(LibraryCompiler.java:148)
        at org.aya.cli.repl.ReplCompiler.loadLibrary(ReplCompiler.java:107)
        at org.aya.cli.repl.ReplCompiler.loadToContext(ReplCompiler.java:99)
        at org.aya.cli.repl.ReplCommands$5.execute(ReplCommands.java:70)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:221)
        at java.base@17.0.5/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.MethodHandleIntrinsicImpl.execute(MethodHandleIntrinsicImpl.java:177)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.methodhandles.Util_java_lang_invoke_MethodHandle.invokeInternal(Target_java_lang_invoke_MethodHandle.java:142)
        at java.base@17.0.5/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:76)
        at java.base@17.0.5/java.lang.invoke.LambdaForm$NamedFunction.invokeWithArguments(LambdaForm.java:96)
        at java.base@17.0.5/java.lang.invoke.LambdaForm.interpretName(LambdaForm.java:964)
        at java.base@17.0.5/java.lang.invoke.LambdaForm.interpretWithArguments(LambdaForm.java:941)
        at java.base@17.0.5/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:82)
        at java.base@17.0.5/java.lang.invoke.MethodHandle.invokeBasic(MethodHandle.java:0)
        at java.base@17.0.5/java.lang.invoke.LambdaForm$MH/0x000000010150c000.invoke_MT(LambdaForm$MH)
        at org.aya.repl.CommandManager$CommandGen.invoke(CommandManager.java:23)
        at org.aya.repl.CommandManager$Clue.run(CommandManager.java:73)
        at org.aya.repl.Repl.loop(Repl.java:31)
        at org.aya.cli.repl.AyaRepl.singleLoop(AyaRepl.java:121)
        at org.aya.cli.repl.AyaRepl.run(AyaRepl.java:110)
        at org.aya.cli.repl.AyaRepl.start(AyaRepl.java:30)
        at org.aya.cli.Main.call(Main.java:40)
        at org.aya.cli.Main.call(Main.java:29)
        at picocli.CommandLine.executeUserObject(CommandLine.java:2041)
        at picocli.CommandLine.access$1500(CommandLine.java:148)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
        at picocli.CommandLine.execute(CommandLine.java:2170)
        at org.aya.cli.Main.main(Main.java:31)

```

**Comment by tsao-chi** [comment]
`kala.function.Hasher$Optimized` and `org.aya.guest0x0.cubical.Formula$Conn` need to be added in reflect config

**Comment by tsao-chi** [comment]
```
:load base/src/test/resources/success
Compiling common
  [Info] Resolving source file dependency
    Done in 257ms
  [Tyck] Relation::Formula (Relation/Formula.aya)
  [Tyck] Primitives (Primitives.aya)
  [Tyck] Intervals (Intervals.aya)
com.oracle.svm.core.jdk.UnsupportedFeatureError: Record components not available for record class org.aya.guest0x0.cubical.Formula$Conn. All record component accessor methods of this record class must be included in the reflection configuration at image build time, then this method can be called.
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.VMError.unsupportedFeature(VMError.java:89)
        at java.base@17.0.5/java.lang.Class.getRecordComponents0(DynamicHub.java:996)
        at java.base@17.0.5/java.lang.Class.getRecordComponents(DynamicHub.java:2436)
```
