### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by imkiva** [aya-prover/aya-dev#83]
This code stably reproduces the out-of-memory error in my machine.

MacBook Air M1 with 16G RAM.
Java: Liberica-17-full build 17+35-LTS

```aya
open data N : Type | zero | suc N

def `+` (a b : N) : N
  | zero, a => a
  | a, zero => a
  | suc a, b => suc (a + b)
  | a, suc b => suc (a + b)

open data Vec (A : Type) (n : N) : Type
  | A, zero => vnil
  | A, suc m => `++` A (Vec A m)

def fold {A R : Type} {n : N} (f : Pi R A -> R) (init : R) (xs : Vec A n) : R
  | {A}, {R}, {zero}, f, init, vnil => init
  | {A}, {R}, {suc m}, f, acc, ++ x xs => fold f (f acc x) xs
```

Stack trace:
<details>
<pre>
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.mapNotNull(ImmutableVectors.java:373)
	at kala.collection/kala.collection.immutable.ImmutableVectors$Vector1.mapNotNull(ImmutableVectors.java:161)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitDataCall(TermFixpoint.java:34)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitDataCall(TermFixpoint.java:18)
	at org.aya/org.aya.core.term.CallTerm$Data.doAccept(CallTerm.java:78)
	at org.aya/org.aya.core.term.Term.accept(Term.java:45)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitRef(TermFixpoint.java:100)
	at org.aya/org.aya.core.visitor.Renamer.lambda$visitRef$0(Renamer.java:27)
	at org.aya/org.aya.core.visitor.Renamer$$Lambda$251/0x0000000800d49278.get(Unknown Source)
	at kala.collection/kala.collection.internal.hash.HashMapBase.getOrElse(HashMapBase.java:345)
	at org.aya/org.aya.core.visitor.Renamer.visitRef(Renamer.java:26)
	at org.aya/org.aya.core.visitor.Renamer.visitRef(Renamer.java:18)
	at org.aya/org.aya.core.term.RefTerm.doAccept(RefTerm.java:16)
	at org.aya/org.aya.core.term.Term.accept(Term.java:45)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitArg(TermFixpoint.java:106)
	at org.aya/org.aya.core.visitor.TermFixpoint.lambda$visitDataCall$2(TermFixpoint.java:33)
	at org.aya/org.aya.core.visitor.TermFixpoint$$Lambda$201/0x0000000800d3a640.apply(Unknown Source)
	at kala.collection/kala.collection.immutable.ImmutableSeqs$Seq2.map(ImmutableSeqs.java:401)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitDataCall(TermFixpoint.java:33)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitDataCall(TermFixpoint.java:18)
	at org.aya/org.aya.core.term.CallTerm$Data.doAccept(CallTerm.java:78)
	at org.aya/org.aya.core.term.Term.accept(Term.java:45)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitRef(TermFixpoint.java:100)
	at org.aya/org.aya.core.visitor.Renamer.lambda$visitRef$0(Renamer.java:27)
	at org.aya/org.aya.core.visitor.Renamer$$Lambda$251/0x0000000800d49278.get(Unknown Source)
	at kala.collection/kala.collection.internal.hash.HashMapBase.getOrElse(HashMapBase.java:345)
	at org.aya/org.aya.core.visitor.Renamer.visitRef(Renamer.java:26)
	at org.aya/org.aya.core.visitor.Renamer.visitRef(Renamer.java:18)
	at org.aya/org.aya.core.term.RefTerm.doAccept(RefTerm.java:16)
	at org.aya/org.aya.core.term.Term.accept(Term.java:45)
	at org.aya/org.aya.core.visitor.TermFixpoint.visitArg(TermFixpoint.java:106)
	at org.aya/org.aya.core.visitor.TermFixpoint.lambda$visitHole$0(TermFixpoint.java:20)

</pre>
</details>

**Comment by ice1000** [comment]
Care to try this patch?

```diff
Index: base/src/main/java/org/aya/core/visitor/Unfolder.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/base/src/main/java/org/aya/core/visitor/Unfolder.java b/base/src/main/java/org/aya/core/visitor/Unfolder.java
--- a/base/src/main/java/org/aya/core/visitor/Unfolder.java	(revision 0324a62163be32fc07b7dd8a92cca16218548ea9)
+++ b/base/src/main/java/org/aya/core/visitor/Unfolder.java	(date 1634279800906)
@@ -77,7 +77,7 @@
     // This shouldn't fail
     // Assertions are enabled optionally, so we could perform some somehow-expensive operations
     assert args.sizeEquals(telescope);
-    assert Term.Param.checkSubst(telescope, args);
+    // assert Term.Param.checkSubst(telescope, args);
     return buildSubst(telescope, args);
   }
 ```

**Comment by ice1000** [comment]
Oh no!
